Extracting and Visualizing Stock Data
Description
Extracting essential data from a dataset and displaying it is a necessary part of data science; therefore individuals can make correct decisions based on the data. In this assignment, you will extract some stock data, you will then display this data in a graph.

In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.1.67)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (5.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->yfinance) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->yfinance) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->yfinance) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->yfinance) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->yfinance) (2025.7.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24->yfinance) (1.17.0)

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
import pandas as pd

In [ ]:
import requests

In [ ]:
import plotly.graph_objects as go

In [ ]:
from plotly.subplots import make_subplots

Impoted the necessary Libraries

In [ ]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021--06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

In [ ]:
import yfinance as yf
tesla = yf.Ticker("TSLA")

In [ ]:
import yfinance as yf
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="5y")
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2020-07-27 00:00:00-04:00,95.666664,103.195999,94.199997,102.639999,240730500,0.0,0.0
1,2020-07-28 00:00:00-04:00,100.266670,104.313332,98.294670,98.432671,237130500,0.0,0.0
2,2020-07-29 00:00:00-04:00,100.066666,102.320663,99.133331,99.940666,141403500,0.0,0.0
3,2020-07-30 00:00:00-04:00,99.199997,100.882668,98.066666,99.166000,114315000,0.0,0.0
4,2020-07-31 00:00:00-04:00,101.000000,101.136665,94.732002,95.384003,183123000,0.0,0.0

In [ ]:
import requests
url = 'https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'

html_data  = requests.get(url).text

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_data, 'html5lib')

In [ ]:
import yfinance as yf
import pandas as pd

tesla = yf.Ticker("TSLA")

# Get Tesla quarterly revenue from Yahoo Finance
tesla_revenue = tesla.quarterly_financials.loc['Total Revenue']
tesla_revenue = pd.DataFrame({
    "Date": tesla_revenue.index,
    "Revenue": tesla_revenue.values / 1_000_000  # Convert to millions
})

print(tesla_revenue)

        Date  Revenue
0 2025-03-31  19335.0
1 2024-12-31  25707.0
2 2024-09-30  25182.0
3 2024-06-30  25500.0
4 2024-03-31  21301.0
5 2023-12-31      NaN

In [ ]:
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].apply(
    lambda x: float(str(x).replace(",", "").replace("$", "")) if pd.notna(x) else 0
)
print(tesla_revenue.head())

        Date  Revenue
0 2025-03-31  19335.0
1 2024-12-31  25707.0
2 2024-09-30  25182.0
3 2024-06-30  25500.0
4 2024-03-31  21301.0

In [ ]:
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

In [ ]:
tesla_revenue.tail()

        Date  Revenue
1 2024-12-31  25707.0
2 2024-09-30  25182.0
3 2024-06-30  25500.0
4 2024-03-31  21301.0
5 2023-12-31      0.0

In [ ]:
gme = yf.Ticker("GME")

In [ ]:
gme_data = gme.history(period="max")

In [ ]:
gme_data.reset_index(inplace=True)

gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716073,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683251,1.687459,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [ ]:
url = 'https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue'

html_data  = requests.get(url).text

In [ ]:
gme_data = gme.history(period="max")

In [ ]:
gme_data.reset_index(inplace=True)

gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683251,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [ ]:
url = 'https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue'

html_data  = requests.get(url).text

In [ ]:
soup = BeautifulSoup(html_data, 'html5lib')

In [ ]:
import yfinance as yf
import pandas as pd

gamestop = yf.Ticker("GME")

# Get quarterly revenue
gme_revenue = gamestop.quarterly_financials.loc["Total Revenue"]
gme_revenue = pd.DataFrame({
    "Date": gme_revenue.index,
    "Revenue": gme_revenue.values / 1_000_000  # Convert to millions
})

print(gme_revenue)

        Date  Revenue
0 2025-04-30    732.4
1 2025-01-31   1282.6
2 2024-10-31    860.3
3 2024-07-31    798.3
4 2024-04-30    881.8
5 2024-01-31      NaN
6 2023-10-31      NaN

In [ ]:
gme_revenue.tail()

        Date  Revenue
2 2024-10-31    860.3
3 2024-07-31    798.3
4 2024-04-30    881.8
5 2024-01-31      NaN
6 2023-10-31      NaN

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def make_graph(stock_data, revenue_data, stock_name):
    fig = make_subplots(
        rows=2, cols=1, shared_xaxes=True,
        subplot_titles=(f"{stock_name} Historical Share Price", f"{stock_name} Revenue"),
        vertical_spacing=0.2
    )

    # Plot stock price
    fig.add_trace(
        go.Scatter(x=stock_data['Date'], y=stock_data['Close'], name="Share Price"),
        row=1, col=1
    )

    # Plot revenue
    fig.add_trace(
        go.Bar(x=revenue_data['Date'], y=revenue_data['Revenue'], name="Revenue"),
        row=2, col=1
    )

    # Labels
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price (USD)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue (Millions USD)", row=2, col=1)

    # Layout
    fig.update_layout(height=800, showlegend=False, title=stock_name,
                      xaxis_rangeslider_visible=True)
    fig.show()

In [ ]:
make_graph(tesla_data, tesla_revenue, "Tesla")

In [ ]:
make_graph(gme_data, gme_revenue, 'GameStop')